name: Build and push docker images

on:
  push:
    branches:
      - "*"

jobs:
  Build_python_36:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make dir
        run: mkdir C:\BuildTools

      - name: Build
        run: docker build -f p36.Dockerfile . -t testbuild:latest